application: pickr
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app

- url: /static
  static_dir: static

libraries:
- name: webapp2
  version: "2.5.1"

- name: jinja2
  version: "2.6"

- name: PIL
  version: latest

- name: numpy
  version: latest